# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout

      - run: sudo apt update
      - run: sudo docker-php-ext-install zip
      - run: sudo pecl install xdebug
      - run: sudo sh -c 'echo "xdebug.mode = coverage" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      # run tests with phpunit or codecept
      - run: ./vendor/bin/phpunit --log-junit tests/logs/phpunit-results.xml
      - run: ./vendor/bin/grumphp run
      - store_test_results:
          path: ./tests/logs/

workflows:

